# Generated by Django 3.2.5 on 2021-07-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=200, verbose_name='Наименование района')),
                ('area_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('area_coefficient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Коэфициэнт стоимости доставки')),
                ('area_description', models.TextField(verbose_name='Описание района')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('order_name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Телефон заказчика')),
                ('order_date_delivery', models.DateTimeField(verbose_name='Дата доставки')),
                ('order_count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('order_address', models.CharField(max_length=500, verbose_name='Адрес доставки')),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('order_description', models.TextField(verbose_name='Описание заказа')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_first__gravel_and_sand.areas')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_first__gravel_and_sand.products')),
            ],
        ),
    ]
