# Generated by Django 3.2.5 on 2021-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0002_auto_20210714_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='areas',
            name='area_coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Коэфициэнт стоимости доставки'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='area_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
