# Generated by Django 3.2.5 on 2021-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0003_auto_20210720_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='area_coefficient',
        ),
        migrations.AlterField(
            model_name='areas',
            name='area_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
