# Generated by Django 3.2.5 on 2021-07-26 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0005_orders_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_time_delivery',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date_delivery',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
    ]
