# Generated by Django 3.2.5 on 2021-07-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0006_auto_20210726_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=200, verbose_name='Наименование статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
