# Generated by Django 3.2.5 on 2021-07-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0007_orderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AddField(
            model_name='orders',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_first__gravel_and_sand.orderstatus'),
        ),
    ]
