# Generated by Django 3.2.5 on 2021-07-28 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0014_auto_20210728_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 57, 35, 521672, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
