# Generated by Django 3.2.5 on 2021-07-29 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0018_auto_20210728_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 6, 50, 15, 721951, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
