# Generated by Django 3.2.5 on 2021-08-04 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0021_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_timezone',
            field=models.CharField(default=3, max_length=6, verbose_name='Timezone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 19, 10, 52, 148183, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
