# Generated by Django 3.2.5 on 2021-08-05 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_first__gravel_and_sand', '0022_auto_20210804_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 29, 40, 222345, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание заказа'),
        ),
    ]
